// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Prisma CLI (db push / migrate) needs a direct connection, not the
    // pgbouncer pooler — so this points at DIRECT_URL, not DATABASE_URL.
    url: env("DIRECT_URL"),
  },
});
